<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>api-students-v1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d16c6836-f3b1-404e-907e-43ee8e57c1ee</testSuiteGuid>
   <testCaseLink>
      <guid>a54baf5a-d300-4fa8-bd38-da49e16b54f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Students Api/Create Token/create token</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0d5c6fcb-54a6-4f68-974f-0db248132ed5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/studentData/createToken</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0d5c6fcb-54a6-4f68-974f-0db248132ed5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>clientId</value>
         <variableId>ad970daa-c9d8-42e2-9ae4-4df493d9f60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d5c6fcb-54a6-4f68-974f-0db248132ed5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>key</value>
         <variableId>dbb64e17-c222-4d76-bea8-6d4a509cb594</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d5c6fcb-54a6-4f68-974f-0db248132ed5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedStatusCode</value>
         <variableId>ea112e02-e8a1-4139-9edf-9923e7bb32a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f7c6a3d-10b5-4431-a8ad-ce72d9120fdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Students Api/students/create/create a student without token</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c19f7324-97a8-460a-ab2b-c2d6819448da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9694dc8-500f-4d39-bb78-cbb5502879ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec7924c0-3117-4daf-b9a4-c633e0a0f5dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c170714-2374-4646-b4be-3c575a39aaac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2e34115-3ad3-4543-a9a2-d287851ee6dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c723c32b-5be0-4dcd-b349-1a63c9e3d399</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7736d11b-3a9f-4dc0-a716-e5ec75100642</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d6ed0dd-b31a-412d-a9ec-fa5993aaf005</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Students Api/students/create/create a student</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e0bd99f8-f152-4c69-b893-4dcbbbb65981</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/studentData/createStudentData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e0bd99f8-f152-4c69-b893-4dcbbbb65981</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>5e139809-4aec-42f7-acd3-75436804f976</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e0bd99f8-f152-4c69-b893-4dcbbbb65981</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>575f29e1-5af7-4fbf-8901-af7f33932494</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e0bd99f8-f152-4c69-b893-4dcbbbb65981</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nationality</value>
         <variableId>e17af872-50eb-4939-867d-454d968ac0e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e0bd99f8-f152-4c69-b893-4dcbbbb65981</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dateOfBirth</value>
         <variableId>84c5f793-992c-4767-88d9-665b47fc666f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e0bd99f8-f152-4c69-b893-4dcbbbb65981</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>bf318d3c-5f99-46b9-a521-e7e595c267a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e0bd99f8-f152-4c69-b893-4dcbbbb65981</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>phoneNumber</value>
         <variableId>452529c9-8e53-45da-bbf5-d38d7beb12de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e0bd99f8-f152-4c69-b893-4dcbbbb65981</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedStatusCode</value>
         <variableId>b9f3dd7f-ab53-4122-bb18-010d65b442cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb3800ae-a707-4149-b274-1250903122f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Students Api/students/view/attempt to view details of an existing student without client id</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51ec8a73-6e06-448f-a7a3-c75c2fe825c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03da0285-6c7a-41be-aa23-b574a842146f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deab2f8d-e1c6-4f61-89d5-96bcc5762894</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a061e6f-b127-4128-9b53-e29571680bb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ceffd94-0062-4053-a685-d76ced8d95c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea7388d-081c-491e-a1b4-df30bf8c4ebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7296a8a-5f2e-407a-8ac4-3c1647b66bb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4f6ce7e-d443-49b3-969c-58450e56cad1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11245aac-74ba-4c80-bc9a-56eed0eb2960</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Students Api/students/view/attempt to view details of an existing student without valid token</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f69682b-56aa-4572-8ae4-2dca1dd60039</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92c1864e-537b-4fa5-b323-54397e5fb7d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8ea5ddf-ba9e-4f84-bb82-1ca2b731148a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f50246de-aae2-4d4c-a338-c2231be775d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d77b7ba3-f58a-49b2-bf94-dcbb84e62c5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7e2df11-4f9e-40cf-b27f-363c2801c684</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16bfca91-b67a-4018-86c0-78438c0c6be4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a72db42f-7cf0-4863-858c-0fbf01daa6a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4c0cda8-29e6-47ea-8422-9da2845d3097</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Students Api/students/view/view all student details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>89ef8be8-8d09-4dab-bb48-82bf508e1283</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Students Api/students/view/view details of an existing student</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8534a283-4220-4a64-9032-af2c61412bcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8833c62-f41b-4fed-b4b1-087d016b871a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dce1529-140f-4e97-9461-67da36cf78ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6011d80e-8d75-47b8-adf7-f14e533bc8cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d185d19f-20f0-4789-b6dc-2e1bd6382e56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c16c4eb6-2f26-48ef-a70e-d73a9196420b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ed5e695-b776-4fb2-ad97-b4026bf0c873</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da5b5b48-7d24-4b43-b60c-3273b87ed231</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
